spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/larp_database
    username: root
    password: coderslab
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
    favicon:
    resources:
      add-mappings: false

security:
  basic:
    enabled: true
  user:
    name: user
    password: password
  roles:
    - name: USER
      password: password
      authorities: ROLE_USER
    - name: ADMIN
      password: admin
      authorities: ROLE_ADMIN

  mail:
    host: smtp.gmail.com
    port: 587
    username: klopsiksalomea@gmail.com
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG