spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/larp_database
    username: root
    password: coderslab
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
    favicon:
    resources:
      add-mappings: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update   # Dodana właściwość ddl-auto
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG